### ISSUE TITLE
runtime_checkable error in newer versions caused by a protocol subclass

### ISSUE THREAD

**Issue by vnmabus** [python/typing_extensions#207]
Consider the following code:
```python
from typing import Sized

isinstance(1, Sized)
```
This works well and returns `False`, as expected.

However, if I create a new protocol that subclass `Sized`:
```python
from typing_extensions import Protocol

class MySized(Protocol, Sized):
    pass

isinstance(1, Sized)
```
This now raises the following exception:

<details>

```python
TypeError                                 Traceback (most recent call last)
<ipython-input-5-2516c5c4af5f> in <module>
----> 1 isinstance(1, Sized)

.../lib/python3.8/typing.py in __instancecheck__(self, obj)
    764 
    765     def __instancecheck__(self, obj):
--> 766         return self.__subclasscheck__(type(obj))
    767 
    768     def __subclasscheck__(self, cls):

.../lib/python3.8/typing.py in __subclasscheck__(self, cls)
    769         if self._special:
    770             if not isinstance(cls, _GenericAlias):
--> 771                 return issubclass(cls, self.__origin__)
    772             if cls._special:
    773                 return issubclass(cls.__origin__, self.__origin__)

.../lib/python3.8/abc.py in __subclasscheck__(cls, subclass)
    100         def __subclasscheck__(cls, subclass):
    101             """Override for issubclass(subclass, cls)."""
--> 102             return _abc_subclasscheck(cls, subclass)
    103 
    104         def _dump_registry(cls, file=None):

.../lib/python3.8/site-packages/typing_extensions.py in __subclasscheck__(cls, other)
    581                     "Protocols with non-method members don't support issubclass()"
    582                 )
--> 583             return super().__subclasscheck__(other)
    584 
    585         def __instancecheck__(cls, instance):

.../lib/python3.8/abc.py in __subclasscheck__(cls, subclass)
    100         def __subclasscheck__(cls, subclass):
    101             """Override for issubclass(subclass, cls)."""
--> 102             return _abc_subclasscheck(cls, subclass)
    103 
    104         def _dump_registry(cls, file=None):

.../lib/python3.8/site-packages/typing_extensions.py in _proto_hook(cls, other)
    637             if _allow_reckless_class_checks():
    638                 return NotImplemented
--> 639             raise TypeError("Instance and class checks can only be used with"
    640                             " @runtime_checkable protocols")
    641 

TypeError: Instance and class checks can only be used with @runtime_checkable protocols
```

</details>

This non-local behavior did not happen in prior versions, and has caused problems in my code (https://github.com/GAA-UAM/scikit-fda/issues/540).

**Comment by AlexWaygood** [comment]
`typing_extensions`'s behaviour is correct here. You can see that it matches the behaviour of the `typing` module on Python >=3.10:

```pycon
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
from typing import Sized, Protocol
class MySized(Sized, Protocol): pass

isinstance(1, MySized)
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    isinstance(1, MySized)
  File "C:\Users\alexw\AppData\Local\Programs\Python\Python311\Lib\typing.py", line 1960, in __instancecheck__
    raise TypeError("Instance and class checks can only be used with"
TypeError: Instance and class checks can only be used with @runtime_checkable protocols
```

Your `MySized` class is a protocol, but it is not a runtime-checkable protocol. If a protocol is not runtime-checkable, you're not allowed to check it at runtime with `isinstance()` or `issubclass()` checks. This is specified in [PEP 544](https://peps.python.org/pep-0544/#runtime-checkable-decorator-and-narrowing-types-by-isinstance). You can fix your code by decorating your `Sized` class with `@typing_extensions.runtime_checkable`.

`typing_extensions` had a bug in previous versions where `TypeError` was not always raised if you called `isinstance()` against a protocol that was not decorated with `@runtime_checkable`. This bug was fixed in v4.6.0, and the fix was documented in the changelog: https://github.com/python/typing_extensions/pull/132.

**Comment by vnmabus** [comment]
I am NOT using `isinstance` with `MySized`, please check the code again.

**Comment by AlexWaygood** [comment]
Yikes, that's not good! Thanks for the report.

**Comment by jgbos** [comment]
@AlexWaygood I'm having similar issues.  One thing I noticed in my issue you might look at, if you run debug on the error is the error thrown with `cls == Sized` or on `cls == MySized`.  I noticed the `TypeError` was thrown on any of protocols without `runtime_checkable`.

**Comment by AlexWaygood** [comment]
@jgbos are you _still_ experiencing this issue with the latest version of `typing_extensions` (4.6.3)?
