### ISSUE TITLE
No tests asserting that TypedDicts cannot inherit from plain `Generic`

### ISSUE THREAD

**Issue by AlexWaygood** [python/typing_extensions#233]
On Python 3.11, using typing_extensions `main`:

```pycon
>>> from typing_extensions import TypedDict
>>> from typing import Generic
>>> class Foo(TypedDict, Generic): pass
>>>
```

On CPython `main` (and Python 3.11), this is what you get:

```pycon
>>> from typing import *
>>> class Foo(TypedDict, Generic): pass
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alexw\coding\cpython\Lib\typing.py", line 2813, in __new__
    tp_dict = type.__new__(_TypedDictMeta, name, (*generic_base, dict), ns)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\typing.py", line 1076, in _generic_init_subclass
    raise TypeError("Cannot inherit from plain Generic")
TypeError: Cannot inherit from plain Generic
```

(The CPython error is correct -- you should be inheriting from `Generic[T]`, not plain `Generic`.)

There don't seem to be any tests over at CPython covering this, so there's a test-coverage bug over at CPython as well.

**Comment by AlexWaygood** [comment]
This also reproduces on 4.6.3, so I don't think there's a recent regression here

**Comment by AlexWaygood** [comment]
Oh no wait. This reproduces on 4.6.3, but _not_ on `main`. I confused myself. We should still add tests though. But maybe over at CPython first :)

**Comment by AlexWaygood** [comment]
Should be fixed in cpython first (and it's minor enough I'm not sure it's even worth a PR over there)
