### ISSUE TITLE
Unit tests fails with Python 3.13.0a2

### ISSUE THREAD

**Issue by hegjon** [python/typing_extensions#326]
More details: https://bugzilla.redhat.com/show_bug.cgi?id=2259519

Output:
```
+ /usr/bin/python3 -m unittest discover
.......................................................................................................................................................s..s..s....................................................................F................................F...............................................................................................s........../builddir/build/BUILD/typing_extensions-4.9.0/src/test_typing_extensions.py:3507: DeprecationWarning: Failing to pass a value for the 'fields' parameter is deprecated and will be disallowed in Python 3.15. To create a TypedDict class with 0 fields using the functional syntax, pass an empty dictionary, e.g. `Emp = TypedDict('Emp', {})`.
  Emp = TypedDict('Emp', name=str, id=int)
...............s........
======================================================================
FAIL: test_generic_protocols_special_from_protocol (test_typing_extensions.ProtocolTests.test_generic_protocols_special_from_protocol)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/typing_extensions-4.9.0/src/test_typing_extensions.py", line 3061, in test_generic_protocols_special_from_protocol
    self.assertEqual(typing_extensions._get_protocol_attrs(PR), {'x'})
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Items in the first set but not the second:
'__non_callable_proto_members__'

======================================================================
FAIL: test_protocol_issubclass_error_message (test_typing_extensions.ProtocolTests.test_protocol_issubclass_error_message)
----------------------------------------------------------------------
TypeError: Instance and class checks can only be used with @runtime_checkable protocols

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/typing_extensions-4.9.0/src/test_typing_extensions.py", line 3471, in test_protocol_issubclass_error_message
    with self.assertRaisesRegex(TypeError, re.escape(expected_error_message)):
        issubclass(int, Vec2D)
AssertionError: "Protocols\ with\ non\-method\ members\ don't\ support\ issubclass\(\)\.\ Non\-method\ members:\ 'x',\ 'y'\." does not match "Instance and class checks can only be used with @runtime_checkable protocols"

----------------------------------------------------------------------
Ran 385 tests in 0.113s

FAILED (failures=2, skipped=5)
```

**Comment by AlexWaygood** [comment]
(The fix has been released as part of typing_extensions 4.10.0, @hegjon :)
