### ISSUE TITLE
PEP-696: `AttributeError: attribute '__default__' of 'typing.ParamSpec' objects is not writable` on Python 3.13

### ISSUE THREAD

**Issue by Zac-HD** [python/typing_extensions#404]
On Python 3.13.0b1, with typing-extensions 4.11.0 (latest at time of writing), [I get an error](https://github.com/HypothesisWorks/hypothesis/actions/runs/9143526585/job/25140283321?pr=3996#step:6:869):

```python-traceback
Traceback (most recent call last):
    ...
    File "hypothesis/hypothesis-python/tests/typing_extensions/test_backported_types.py", line 187, in test_callable_with_paramspec
      P = ParamSpec("P")
    File "python3.13/site-packages/typing_extensions.py", line 1512, in __new__
      _set_default(paramspec, default)
    File "python3.13/site-packages/typing_extensions.py", line 1375, in _set_default
      type_param.__default__ = None
  AttributeError: attribute '__default__' of 'typing.ParamSpec' objects is not writable
```

This looks like a bug, maybe related to https://github.com/python/typing_extensions/issues/396.

**Comment by AlexWaygood** [comment]
This should be already fixed in 4.12.0rc1! Could you try that and see if you get any errors? I think we're planning on cutting the release properly tomorrow if there are no bugs reported from people testing the release candidate

**Comment by AlexWaygood** [comment]
(This is a duplicate of #377
;)

**Comment by JelleZijlstra** [comment]
> This should be already fixed in 4.12.0rc1! Could you try that and see if you get any errors? I think we're planning on cutting the release properly tomorrow if there are no bugs reported from people testing the release candidate

The new release should come out on Thursday, so a few more days than tomorrow.

**Comment by Zac-HD** [comment]
Happy to confirm that the release candidate solves my issue.  Thanks all!

**Comment by kylewee** [comment]
> > This should be already fixed in 4.12.0rc1! Could you try that and see if you get any errors? I think we're planning on cutting the release properly tomorrow if there are no bugs reported from people testing the release candidate
> 
> The new release should come out on Thursday, so a few more days than tomorrow.

it"s been 1 year

**Comment by AlexWaygood** [comment]
> it"s been 1 year

A year with multiple feature-packed `typing_extensions` releases 🥳 https://github.com/python/typing_extensions/releases
