### ISSUE TITLE
Test regression with pypy3.9: test_overload_on_compiled_functions

### ISSUE THREAD

**Issue by mgorny** [python/typing_extensions#83]
```pytb
$ pypy3 --version
Python 3.9.12 (05fbe3aa5b0845e6c37239768aa455451aa5faba, Sep 05 2022, 05:41:51)
[PyPy 7.3.9 with GCC 12.2.1 20220903]
$ tox -e pypy3
pypy3 inst-nodeps: /tmp/typing_extensions/.tox/.tmp/package/1/typing_extensions-4.4.0.tar.gz
pypy3 installed: cffi==1.15.0,greenlet==0.4.13,hpy==0.0.3,readline==6.2.4.1,typing_extensions @ file:///tmp/typing_extensions/.tox/.tmp/package/1/typing_extensions-4.4.0.tar.gz
pypy3 run-test-pre: PYTHONHASHSEED='150667971'
pypy3 run-test: commands[0] | python -m unittest discover
..................s...........................................................................................s.s..s...............................F.................................................Runtime type is 'object'
......................................................s.........
======================================================================
FAIL: test_overload_on_compiled_functions (test_typing_extensions.OverloadTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pypy3.9/unittest/mock.py", line 1336, in patched
    return func(*newargs, **newkeywargs)
  File "/tmp/typing_extensions/src/test_typing_extensions.py", line 526, in test_overload_on_compiled_functions
    self.assertEqual(get_overloads(sum), [])
AssertionError: Lists differ: [<built-in function sum>] != []

First list contains 1 additional elements.
First extra element 0:
<built-in function sum>

- [<built-in function sum>]
+ []

----------------------------------------------------------------------
Ran 261 tests in 0.253s

FAILED (failures=1, skipped=5)
ERROR: InvocationError for command /tmp/typing_extensions/.tox/pypy3/bin/python -m unittest discover (exited with code 1)
_______________________________________________________________ summary _______________________________________________________________
ERROR:   pypy3: commands failed
```

**Comment by srittau** [comment]
One preliminary note: As the implementation of `overload` matches the implementation of `overload` in Python 3.11, pypy would also fail with the `typing.py` module from there.

**Comment by srittau** [comment]
The problem is that `sum()` and `print()` are not compiled functions in pypy. The test in question checks whether `@overload` is skipped for those, so it can't work. #84 just skips this tests when running pypy.

**Comment by mgorny** [comment]
Thanks. This makes sense to me.
